name: Deploy Outbreak.info Webapp to S3

on:
  push:
    branches:
    - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm --prefix web/ install
    - name: build website
      env:
        VUE_APP_API_ACCESS: ${{ secrets.VUE_APP_API_ACCESS }}
      run: npm --prefix web/ run build
    - name: sync s3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.OUTBREAK_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: './web/dist'
        DEST_DIR: 'master'
    - name: invalidate cloudfront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        PATHS: "/*"
        AWS_REGION: ${{ secrets.AWS_REGION }}
        DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
